name: DeployGenerators

on:
  push:
    branches:
      - main
      
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Set AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Deploy
        run: |
          cd generators
          zip -r generators.zip ./*
          aws lambda update-function-code --function-name=generators --zip-file=fileb://generators.zip
